spring:
  config:
    activate:
      on-profile: test
    import:
      - classpath:jpa.yaml
      - classpath:external.yaml
      - classpath:security.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:
    driver-class-name: ${DB_DRIVER_CLASS}
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://${REDIS_HOST:localhost}:${REDIS_PORT:6382}"
          password: "${REDIS_PASSWORD:}"
          database: 0
          connectionPoolSize: 3
          connectionMinimumIdleSize: 0
          timeout: 3000
          connectTimeout: 2000
          idleConnectionTimeout: 5000
          retryAttempts: 2
          retryInterval: 500
          dnsMonitoringInterval: -1
        threads: 2
        nettyThreads: 2
        codec: !<org.redisson.codec.JsonJacksonCodec> {}

management:
  endpoints:
    web:
      exposure:
        include: health
