spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:jpa.yaml
      - classpath:external.yaml
      - classpath:security.yaml
      - classpath:monitoring.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  redis:
    host: ${REDIS_HOST:}
    port: ${REDIS_PORT:}
    password: ${REDIS_PASSWORD:}
  web:
    resources:
      add-mappings: false
