spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:jpa.yaml
      - classpath:external.yaml
      - classpath:jwt.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

management:
  endpoints:
    web:
      exposure:
        include: health
