spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:jpa.yaml
      - classpath:external.yaml
      - classpath:monitoring.yaml
      - classpath:security.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
  redis:
    host: ${REDIS_HOST:platform-redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  web:
    resources:
      add-mappings: false
