spring:
  main:
    lazy-initialization: true
  config:
    activate:
      on-profile: dev
    import:
      - classpath:jpa.yaml
      - classpath:external.yaml
      - classpath:security.yaml
      - classpath:monitoring.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
    hikari:
      maximum-pool-size: 1
      minimum-idle: 0
      connection-timeout: 5000
      idle-timeout: 30000
      max-lifetime: 60000
      validation-timeout: 2000
      leak-detection-threshold: 20000
      connection-test-query: SELECT 1
      register-mbeans: false
  redis:
    host: ${REDIS_HOST:}
    port: ${REDIS_PORT:}
    password: ${REDIS_PASSWORD:}
  web:
    resources:
      add-mappings: false
