spring:
  config:
    activate:
      on-profile: test
    import:
      - classpath:jpa.yaml
      - classpath:external.yaml
      - classpath:security.yaml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:
    driver-class-name: ${DB_DRIVER_CLASS}

security:
  x-api-key: ${X_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health