spring:
  config:
    activate.on-profile:
      - prod
      - dev
      - local
      - test

external:
  gabia:
    sms:
      id: ${GABIA_SMS_ID}
      key: ${GABIA_SMS_KEY}
      url: ${GABIA_SMS_URL}
      phone: ${GABIA_SMS_PHONE}
  oauth:
    apple:
      web-aud: ${APPLE_AUD_WEB}
      app-aud: ${APPLE_AUD_APP}
    google:
      client:
        id: ${GOOGLE_CLIENT_ID}
    magic-login:
      phone: ${MAGIC_LOGIN_PHONE}
      code: ${MAGIC_LOGIN_CODE}
      name: ${MAGIC_LOGIN_NAME}
