spring.config.activate.on-profile:
  - prod
  - dev
  - local
  - test

security:
  api:
    keys:
      playground: ${PLAYGROUND_X_API_KEY}
      crew: ${CREW_X_API_KEY}
      app: ${APP_X_API_KEY}
      admin: ${ADMIN_X_API_KEY}
      platform: ${PLATFORM_X_API_KEY}
      monitoring: ${MONITORING_X_API_KEY}
    secured-endpoints:
      - ${GET_PUBLIC_KEY}
      - ${ACTUATOR_PATH}
      - ${USER_PATH}

  jwt:
    secret:
      rsa:
        key-id: ${KEY_ID}
        public-key: ${RSA_PUBLIC_KEY_PATH}
        private-key: ${RSA_PRIVATE_KEY_PATH}
      expiration:
        access-token-expiration: ${ACCESS_TOKEN_EXPIRATION_TIME}
        refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION_TIME}
      issuer:
        issuer-name: ${ISSUER}
