name: Continuous Integration for SOPT Makers Authentication Project

on:
  pull_request:
    branches: [ dev, prod ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: ⚙️ Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: 🔑 Create gradle.properties
        run: |
          cat <<EOF > gradle.properties
          ${{ secrets.PROPERTY_GRADLE }}
          EOF

      - name: 🔑 Create test.env in classpath
        run: |
          mkdir -p src/test/resources/env
          cat <<'EOF' > src/test/resources/env/test.env
            ${{ secrets.ENV_FILE_TEST }}
          EOF

      - name: 🧱 Build (context load only)
        run: |
          set -e
          ./gradlew clean build --no-daemon --no-build-cache -Pprofile=test